site_name: Epoch Engine Docs
site_url: https://windokk.github.io/epoch
repo_url: https://github.com/Windokk/Epoch
repo_name: Windokk/EPOCH
copyright: Copyright &copy; 2025 - Windokk
extra:
  version:
    provider: mike
plugins:
  - search
  - tags
  - redirects:
      redirect_maps:
        'index.md': 'index/index.md'



theme:
  features:
    - navigation.expand
    - navigation.tabs
  name: material
  logo: images/EpochLogoDarkMode.png
  icon:
    repo: fontawesome/brands/github
    
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: octicons/gear-16
        name: System preference
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/toggle-switch
        name: Light mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Dark mode

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_css:
  - stylesheets/extra.css